services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    volumes:
      - .:/backend
    networks:
      - backend-network
    env_file:
      - .env

networks:
  backend-network:
    driver: bridge
